<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['TPLPO_Purchaseorderout'] = array(
	'table'=>'tplpo_purchaseorderout',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'po_value' => 
  array (
    'required' => true,
    'name' => 'po_value',
    'vname' => 'LBL_PO_VALUE',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Total value of the PO',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'currency_id' => 
  array (
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY',
    'type' => 'currency_id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => 'visible',
    'function' => 
    array (
      'name' => 'getCurrencyDropDown',
      'returns' => 'html',
    ),
  ),
  'description' => 
  array (
    'name' => 'description',
    'vname' => 'LBL_DESCRIPTION',
    'type' => 'text',
    'comment' => 'Full text of the note',
    'rows' => '6',
    'cols' => '80',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Full text of the note',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
  ),
  'profiling_allocated' => 
  array (
    'required' => false,
    'name' => 'profiling_allocated',
    'vname' => 'LBL_PROFILING_ALLOCATED',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any profiling allocated to projects',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'tele_allocated' => 
  array (
    'required' => false,
    'name' => 'tele_allocated',
    'vname' => 'LBL_TELE_ALLOCATED',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of the tele marketing allocated',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'proj_man_component' => 
  array (
    'required' => true,
    'name' => 'proj_man_component',
    'vname' => 'LBL_PROJ_MAN_COMPONENT',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any project management component',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'proj_man_allocated' => 
  array (
    'required' => false,
    'name' => 'proj_man_allocated',
    'vname' => 'LBL_PROJ_MAN_ALLOCATED',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any project management allocated',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'other_component' => 
  array (
    'required' => true,
    'name' => 'other_component',
    'vname' => 'LBL_OTHER_COMPONENT',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any other component',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'tele_component' => 
  array (
    'required' => true,
    'name' => 'tele_component',
    'vname' => 'LBL_TELE_COMPONENT',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of the tele marketing component',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'profiling_component' => 
  array (
    'required' => true,
    'name' => 'profiling_component',
    'vname' => 'LBL_PROFILING_COMPONENT',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any profiling component',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'other_allocated' => 
  array (
    'required' => false,
    'name' => 'other_allocated',
    'vname' => 'LBL_OTHER_ALLOCATED',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any other component allocated',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'po_total' => 
  array (
    'required' => false,
    'name' => 'po_total',
    'vname' => 'LBL_PO_TOTAL',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any other component',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'po_start_date' => 
  array (
    'required' => true,
    'name' => 'po_start_date',
    'vname' => 'LBL_PO_START_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'PO Start Date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'po_end_date' => 
  array (
    'required' => false,
    'name' => 'po_end_date',
    'vname' => 'LBL_PO_END_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'PO End Date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'po_total_allocated' => 
  array (
    'required' => false,
    'name' => 'po_total_allocated',
    'vname' => 'LBL_PO_TOTAL_ALLOCATED',
    'type' => 'currency',
    'massupdate' => 0,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Value of any other component',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'name' => 
  array (
    'name' => 'name',
    'vname' => 'LBL_NAME',
    'type' => 'name',
    'link' => true,
    'dbType' => 'varchar',
    'len' => '255',
    'unified_search' => false,
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'required' => true,
    'importable' => 'required',
    'duplicate_merge' => 'disabled',
    'merge_filter' => 'disabled',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Clints PO / Order Number',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'size' => '20',
  ),
  'tplsu_tpl_suppliers_id_c' => 
  array (
    'required' => false,
    'name' => 'tplsu_tpl_suppliers_id_c',
    'vname' => 'LBL_SUPPLIER_TPLSU_TPL_SUPPLIERS_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'supplier' => 
  array (
    'required' => true,
    'source' => 'non-db',
    'name' => 'supplier',
    'vname' => 'LBL_SUPPLIER',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'tplsu_tpl_suppliers_id_c',
    'ext2' => 'TPLSU_TPL_Suppliers',
    'module' => 'TPLSU_TPL_Suppliers',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'document_id_c' => 
  array (
    'required' => false,
    'name' => 'document_id_c',
    'vname' => 'LBL_PURCHASEORDER_DOCUMENT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'purchaseorder' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'purchaseorder',
    'vname' => 'LBL_PURCHASEORDER',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'document_id_c',
    'ext2' => 'Documents',
    'module' => 'Documents',
    'rname' => 'document_name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('TPLPO_Purchaseorderout','TPLPO_Purchaseorderout', array('basic','assignable'));